# Workflow to build Java project with Maven.
name: Java CI with Maven in Linux

on:
  push:
    # Exclude CI build when there are changes only in the following paths.
    paths-ignore:
      - '**/.github/workflows/**'
      - '**/.gitignore'
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      workdir: io.github.davidedelbimbo.music-store
    strategy:
      matrix:
        include:
          - java: 8
            additional-maven-args: >
              -Pcoveralls
              -DrepoToken=$COVERALLS_REPO_TOKEN
              -DpullRequest=${{ github.event.pull_request.number }}
          - java: 11

    name: Build with Java ${{ matrix.java }} on Linux
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Set up JDK ${{ matrix.java }}
      uses: actions/setup-java@v4
      with:
        java-version: ${{ matrix.java }}
        distribution: 'temurin'
    - name: Cache Maven packages
      uses: actions/cache@v4
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml', '**/*.yml') }}
        restore-keys: ${{ runner.os }}-m2-
    - name: Build with Maven
      run: >
        mvn verify
        ${{ matrix.additional-maven-args }}
      working-directory: ${{ env.workdir }}
      env:
        COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
    - name: Generate Unit Test Report
      run: mvn surefire-report:report-only site:site -DgenerateReports=false
      working-directory: ${{ env.workdir }}
      if: ${{ always() }}
    - name: Generate Integration Test Report
      run: mvn surefire-report:failsafe-report-only site:site -DgenerateReports=false
      working-directory: ${{ env.workdir }}
      if: ${{ always() }}
    - name: Archive JUnit Reports
      uses: actions/upload-artifact@v4
      if: ${{ always() }}
      with:
        name: surefire-report-jdk-${{ matrix.java }}
        path: '**/target/site'